/**
 * Email delivery for recommendations — PRD 04 (REQ-REC-005)
 */

function buildRepEmail(recommendation, repName, dashboardBaseUrl) {
  const { score_snapshot, recommendations, highlights } = recommendation.content;
  const delta = score_snapshot.delta >= 0 ? `+${score_snapshot.delta}` : `${score_snapshot.delta}`;
  const arrow = score_snapshot.delta > 0 ? '▲' : score_snapshot.delta < 0 ? '▼' : '→';

  const recList = recommendations
    .slice(0, 3)
    .map((r, i) => `${i + 1}. ${r.action}`)
    .join('\n');

  const highlightList = highlights.map(h => `- ${h}`).join('\n');

  return {
    subject: `Your Weekly Sales Coaching Summary — ${recommendation.period_start} to ${recommendation.period_end}`,
    body: `Hi ${repName},

Your overall coaching score this week: ${score_snapshot.overall}/10 (${arrow} ${delta} from last week)

TOP RECOMMENDATIONS:
${recList}

WHAT YOU DID WELL:
${highlightList}

View your full coaching report: ${dashboardBaseUrl}/rep/${recommendation.recipient_id}

---
This email was generated by the Sales Coaching Tool.`,
  };
}

function buildManagerEmail(recommendation, managerName, dashboardBaseUrl) {
  const { score_snapshot, recommendations, highlights } = recommendation.content;
  const delta = score_snapshot.delta >= 0 ? `+${score_snapshot.delta}` : `${score_snapshot.delta}`;

  return {
    subject: `Team Coaching Summary — ${recommendation.period_start} to ${recommendation.period_end}`,
    body: `Hi ${managerName},

Your team's average coaching score: ${score_snapshot.overall}/10 (${delta} from last period)

${recommendation.content.summary}

TOP ACTIONS:
${recommendations.slice(0, 3).map((r, i) => `${i + 1}. ${r.action}`).join('\n')}

View full team report: ${dashboardBaseUrl}/manager/${recommendation.recipient_id}

---
This email was generated by the Sales Coaching Tool.`,
  };
}

async function deliverRecommendationEmails(db, emailClient, recommendations, dashboardBaseUrl) {
  const results = [];
  for (const rec of recommendations) {
    const member = await db.getTeamMember(rec.recipient_id);
    if (!member) continue;

    let email;
    if (rec.recipient_role === 'rep') {
      email = buildRepEmail(rec, member.name, dashboardBaseUrl);
    } else if (rec.recipient_role === 'manager') {
      email = buildManagerEmail(rec, member.name, dashboardBaseUrl);
    } else {
      continue;
    }

    try {
      await emailClient.send({
        to: member.email,
        subject: email.subject,
        text: email.body,
      });
      await db.markRecommendationDelivered(rec.id, 'email');
      results.push({ id: rec.id, status: 'sent' });
    } catch (err) {
      results.push({ id: rec.id, status: 'error', error: err.message });
    }
  }
  return results;
}

module.exports = { buildRepEmail, buildManagerEmail, deliverRecommendationEmails };
